/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AiWebsiteBootcampRouteImport } from './routes/ai-website-bootcamp'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as RefCallbackRouteImport } from './routes/ref/callback'
import { Route as RefRefCodeRouteImport } from './routes/ref/$refCode'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authUpdatePasswordRouteImport } from './routes/(auth)/update-password'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedOptcontrolRouteRouteImport } from './routes/_authenticated/optcontrol/route'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReferralsIndexRouteImport } from './routes/_authenticated/referrals/index'
import { Route as AuthenticatedPayoutsIndexRouteImport } from './routes/_authenticated/payouts/index'
import { Route as AuthenticatedOptcontrolIndexRouteImport } from './routes/_authenticated/optcontrol/index'
import { Route as AuthenticatedEarningsIndexRouteImport } from './routes/_authenticated/earnings/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedOptcontrolSettingsRouteImport } from './routes/_authenticated/optcontrol/settings'
import { Route as AuthenticatedOptcontrolPayoutsRouteImport } from './routes/_authenticated/optcontrol/payouts'
import { Route as AuthenticatedOptcontrolPaymentsRouteImport } from './routes/_authenticated/optcontrol/payments'
import { Route as AuthenticatedOptcontrolInfluencersRouteImport } from './routes/_authenticated/optcontrol/influencers'
import { Route as AuthenticatedOptcontrolConversionsRouteImport } from './routes/_authenticated/optcontrol/conversions'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedOptcontrolReferralsRouteRouteImport } from './routes/_authenticated/optcontrol/referrals/route'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AiWebsiteBootcampRoute = AiWebsiteBootcampRouteImport.update({
  id: '/ai-website-bootcamp',
  path: '/ai-website-bootcamp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RefCallbackRoute = RefCallbackRouteImport.update({
  id: '/ref/callback',
  path: '/ref/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const RefRefCodeRoute = RefRefCodeRouteImport.update({
  id: '/ref/$refCode',
  path: '/ref/$refCode',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authUpdatePasswordRoute = authUpdatePasswordRouteImport.update({
  id: '/(auth)/update-password',
  path: '/update-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOptcontrolRouteRoute =
  AuthenticatedOptcontrolRouteRouteImport.update({
    id: '/optcontrol',
    path: '/optcontrol',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReferralsIndexRoute =
  AuthenticatedReferralsIndexRouteImport.update({
    id: '/referrals/',
    path: '/referrals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayoutsIndexRoute =
  AuthenticatedPayoutsIndexRouteImport.update({
    id: '/payouts/',
    path: '/payouts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOptcontrolIndexRoute =
  AuthenticatedOptcontrolIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOptcontrolRouteRoute,
  } as any)
const AuthenticatedEarningsIndexRoute =
  AuthenticatedEarningsIndexRouteImport.update({
    id: '/earnings/',
    path: '/earnings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedOptcontrolSettingsRoute =
  AuthenticatedOptcontrolSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOptcontrolRouteRoute,
  } as any)
const AuthenticatedOptcontrolPayoutsRoute =
  AuthenticatedOptcontrolPayoutsRouteImport.update({
    id: '/payouts',
    path: '/payouts',
    getParentRoute: () => AuthenticatedOptcontrolRouteRoute,
  } as any)
const AuthenticatedOptcontrolPaymentsRoute =
  AuthenticatedOptcontrolPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedOptcontrolRouteRoute,
  } as any)
const AuthenticatedOptcontrolInfluencersRoute =
  AuthenticatedOptcontrolInfluencersRouteImport.update({
    id: '/influencers',
    path: '/influencers',
    getParentRoute: () => AuthenticatedOptcontrolRouteRoute,
  } as any)
const AuthenticatedOptcontrolConversionsRoute =
  AuthenticatedOptcontrolConversionsRouteImport.update({
    id: '/conversions',
    path: '/conversions',
    getParentRoute: () => AuthenticatedOptcontrolRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOptcontrolReferralsRouteRoute =
  AuthenticatedOptcontrolReferralsRouteRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedOptcontrolRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/ai-website-bootcamp': typeof AiWebsiteBootcampRoute
  '/checkout': typeof CheckoutRoute
  '/optcontrol': typeof AuthenticatedOptcontrolRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/update-password': typeof authUpdatePasswordRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/ref/$refCode': typeof RefRefCodeRoute
  '/ref/callback': typeof RefCallbackRoute
  '/optcontrol/referrals': typeof AuthenticatedOptcontrolReferralsRouteRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/optcontrol/conversions': typeof AuthenticatedOptcontrolConversionsRoute
  '/optcontrol/influencers': typeof AuthenticatedOptcontrolInfluencersRoute
  '/optcontrol/payments': typeof AuthenticatedOptcontrolPaymentsRoute
  '/optcontrol/payouts': typeof AuthenticatedOptcontrolPayoutsRoute
  '/optcontrol/settings': typeof AuthenticatedOptcontrolSettingsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/earnings/': typeof AuthenticatedEarningsIndexRoute
  '/optcontrol/': typeof AuthenticatedOptcontrolIndexRoute
  '/payouts/': typeof AuthenticatedPayoutsIndexRoute
  '/referrals/': typeof AuthenticatedReferralsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/ai-website-bootcamp': typeof AiWebsiteBootcampRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/update-password': typeof authUpdatePasswordRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/ref/$refCode': typeof RefRefCodeRoute
  '/ref/callback': typeof RefCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/optcontrol/referrals': typeof AuthenticatedOptcontrolReferralsRouteRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/optcontrol/conversions': typeof AuthenticatedOptcontrolConversionsRoute
  '/optcontrol/influencers': typeof AuthenticatedOptcontrolInfluencersRoute
  '/optcontrol/payments': typeof AuthenticatedOptcontrolPaymentsRoute
  '/optcontrol/payouts': typeof AuthenticatedOptcontrolPayoutsRoute
  '/optcontrol/settings': typeof AuthenticatedOptcontrolSettingsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/earnings': typeof AuthenticatedEarningsIndexRoute
  '/optcontrol': typeof AuthenticatedOptcontrolIndexRoute
  '/payouts': typeof AuthenticatedPayoutsIndexRoute
  '/referrals': typeof AuthenticatedReferralsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/ai-website-bootcamp': typeof AiWebsiteBootcampRoute
  '/checkout': typeof CheckoutRoute
  '/_authenticated/optcontrol': typeof AuthenticatedOptcontrolRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/update-password': typeof authUpdatePasswordRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/ref/$refCode': typeof RefRefCodeRoute
  '/ref/callback': typeof RefCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/optcontrol/referrals': typeof AuthenticatedOptcontrolReferralsRouteRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/optcontrol/conversions': typeof AuthenticatedOptcontrolConversionsRoute
  '/_authenticated/optcontrol/influencers': typeof AuthenticatedOptcontrolInfluencersRoute
  '/_authenticated/optcontrol/payments': typeof AuthenticatedOptcontrolPaymentsRoute
  '/_authenticated/optcontrol/payouts': typeof AuthenticatedOptcontrolPayoutsRoute
  '/_authenticated/optcontrol/settings': typeof AuthenticatedOptcontrolSettingsRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/earnings/': typeof AuthenticatedEarningsIndexRoute
  '/_authenticated/optcontrol/': typeof AuthenticatedOptcontrolIndexRoute
  '/_authenticated/payouts/': typeof AuthenticatedPayoutsIndexRoute
  '/_authenticated/referrals/': typeof AuthenticatedReferralsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-website-bootcamp'
    | '/checkout'
    | '/optcontrol'
    | '/settings'
    | '/forgot-password'
    | '/sign-in'
    | '/update-password'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/ref/$refCode'
    | '/ref/callback'
    | '/optcontrol/referrals'
    | '/errors/$error'
    | '/optcontrol/conversions'
    | '/optcontrol/influencers'
    | '/optcontrol/payments'
    | '/optcontrol/payouts'
    | '/optcontrol/settings'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/dashboard/'
    | '/earnings/'
    | '/optcontrol/'
    | '/payouts/'
    | '/referrals/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ai-website-bootcamp'
    | '/checkout'
    | '/forgot-password'
    | '/sign-in'
    | '/update-password'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/ref/$refCode'
    | '/ref/callback'
    | '/'
    | '/optcontrol/referrals'
    | '/errors/$error'
    | '/optcontrol/conversions'
    | '/optcontrol/influencers'
    | '/optcontrol/payments'
    | '/optcontrol/payouts'
    | '/optcontrol/settings'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/dashboard'
    | '/earnings'
    | '/optcontrol'
    | '/payouts'
    | '/referrals'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/ai-website-bootcamp'
    | '/checkout'
    | '/_authenticated/optcontrol'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in'
    | '/(auth)/update-password'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/ref/$refCode'
    | '/ref/callback'
    | '/_authenticated/'
    | '/_authenticated/optcontrol/referrals'
    | '/_authenticated/errors/$error'
    | '/_authenticated/optcontrol/conversions'
    | '/_authenticated/optcontrol/influencers'
    | '/_authenticated/optcontrol/payments'
    | '/_authenticated/optcontrol/payouts'
    | '/_authenticated/optcontrol/settings'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/dashboard/'
    | '/_authenticated/earnings/'
    | '/_authenticated/optcontrol/'
    | '/_authenticated/payouts/'
    | '/_authenticated/referrals/'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AiWebsiteBootcampRoute: typeof AiWebsiteBootcampRoute
  CheckoutRoute: typeof CheckoutRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authUpdatePasswordRoute: typeof authUpdatePasswordRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  RefRefCodeRoute: typeof RefRefCodeRoute
  RefCallbackRoute: typeof RefCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-website-bootcamp': {
      id: '/ai-website-bootcamp'
      path: '/ai-website-bootcamp'
      fullPath: '/ai-website-bootcamp'
      preLoaderRoute: typeof AiWebsiteBootcampRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ref/callback': {
      id: '/ref/callback'
      path: '/ref/callback'
      fullPath: '/ref/callback'
      preLoaderRoute: typeof RefCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ref/$refCode': {
      id: '/ref/$refCode'
      path: '/ref/$refCode'
      fullPath: '/ref/$refCode'
      preLoaderRoute: typeof RefRefCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/update-password': {
      id: '/(auth)/update-password'
      path: '/update-password'
      fullPath: '/update-password'
      preLoaderRoute: typeof authUpdatePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/optcontrol': {
      id: '/_authenticated/optcontrol'
      path: '/optcontrol'
      fullPath: '/optcontrol'
      preLoaderRoute: typeof AuthenticatedOptcontrolRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/referrals/': {
      id: '/_authenticated/referrals/'
      path: '/referrals'
      fullPath: '/referrals/'
      preLoaderRoute: typeof AuthenticatedReferralsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payouts/': {
      id: '/_authenticated/payouts/'
      path: '/payouts'
      fullPath: '/payouts/'
      preLoaderRoute: typeof AuthenticatedPayoutsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/optcontrol/': {
      id: '/_authenticated/optcontrol/'
      path: '/'
      fullPath: '/optcontrol/'
      preLoaderRoute: typeof AuthenticatedOptcontrolIndexRouteImport
      parentRoute: typeof AuthenticatedOptcontrolRouteRoute
    }
    '/_authenticated/earnings/': {
      id: '/_authenticated/earnings/'
      path: '/earnings'
      fullPath: '/earnings/'
      preLoaderRoute: typeof AuthenticatedEarningsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/optcontrol/settings': {
      id: '/_authenticated/optcontrol/settings'
      path: '/settings'
      fullPath: '/optcontrol/settings'
      preLoaderRoute: typeof AuthenticatedOptcontrolSettingsRouteImport
      parentRoute: typeof AuthenticatedOptcontrolRouteRoute
    }
    '/_authenticated/optcontrol/payouts': {
      id: '/_authenticated/optcontrol/payouts'
      path: '/payouts'
      fullPath: '/optcontrol/payouts'
      preLoaderRoute: typeof AuthenticatedOptcontrolPayoutsRouteImport
      parentRoute: typeof AuthenticatedOptcontrolRouteRoute
    }
    '/_authenticated/optcontrol/payments': {
      id: '/_authenticated/optcontrol/payments'
      path: '/payments'
      fullPath: '/optcontrol/payments'
      preLoaderRoute: typeof AuthenticatedOptcontrolPaymentsRouteImport
      parentRoute: typeof AuthenticatedOptcontrolRouteRoute
    }
    '/_authenticated/optcontrol/influencers': {
      id: '/_authenticated/optcontrol/influencers'
      path: '/influencers'
      fullPath: '/optcontrol/influencers'
      preLoaderRoute: typeof AuthenticatedOptcontrolInfluencersRouteImport
      parentRoute: typeof AuthenticatedOptcontrolRouteRoute
    }
    '/_authenticated/optcontrol/conversions': {
      id: '/_authenticated/optcontrol/conversions'
      path: '/conversions'
      fullPath: '/optcontrol/conversions'
      preLoaderRoute: typeof AuthenticatedOptcontrolConversionsRouteImport
      parentRoute: typeof AuthenticatedOptcontrolRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/optcontrol/referrals': {
      id: '/_authenticated/optcontrol/referrals'
      path: '/referrals'
      fullPath: '/optcontrol/referrals'
      preLoaderRoute: typeof AuthenticatedOptcontrolReferralsRouteRouteImport
      parentRoute: typeof AuthenticatedOptcontrolRouteRoute
    }
  }
}

interface AuthenticatedOptcontrolRouteRouteChildren {
  AuthenticatedOptcontrolReferralsRouteRoute: typeof AuthenticatedOptcontrolReferralsRouteRoute
  AuthenticatedOptcontrolConversionsRoute: typeof AuthenticatedOptcontrolConversionsRoute
  AuthenticatedOptcontrolInfluencersRoute: typeof AuthenticatedOptcontrolInfluencersRoute
  AuthenticatedOptcontrolPaymentsRoute: typeof AuthenticatedOptcontrolPaymentsRoute
  AuthenticatedOptcontrolPayoutsRoute: typeof AuthenticatedOptcontrolPayoutsRoute
  AuthenticatedOptcontrolSettingsRoute: typeof AuthenticatedOptcontrolSettingsRoute
  AuthenticatedOptcontrolIndexRoute: typeof AuthenticatedOptcontrolIndexRoute
}

const AuthenticatedOptcontrolRouteRouteChildren: AuthenticatedOptcontrolRouteRouteChildren =
  {
    AuthenticatedOptcontrolReferralsRouteRoute:
      AuthenticatedOptcontrolReferralsRouteRoute,
    AuthenticatedOptcontrolConversionsRoute:
      AuthenticatedOptcontrolConversionsRoute,
    AuthenticatedOptcontrolInfluencersRoute:
      AuthenticatedOptcontrolInfluencersRoute,
    AuthenticatedOptcontrolPaymentsRoute: AuthenticatedOptcontrolPaymentsRoute,
    AuthenticatedOptcontrolPayoutsRoute: AuthenticatedOptcontrolPayoutsRoute,
    AuthenticatedOptcontrolSettingsRoute: AuthenticatedOptcontrolSettingsRoute,
    AuthenticatedOptcontrolIndexRoute: AuthenticatedOptcontrolIndexRoute,
  }

const AuthenticatedOptcontrolRouteRouteWithChildren =
  AuthenticatedOptcontrolRouteRoute._addFileChildren(
    AuthenticatedOptcontrolRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOptcontrolRouteRoute: typeof AuthenticatedOptcontrolRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedEarningsIndexRoute: typeof AuthenticatedEarningsIndexRoute
  AuthenticatedPayoutsIndexRoute: typeof AuthenticatedPayoutsIndexRoute
  AuthenticatedReferralsIndexRoute: typeof AuthenticatedReferralsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOptcontrolRouteRoute:
    AuthenticatedOptcontrolRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedEarningsIndexRoute: AuthenticatedEarningsIndexRoute,
  AuthenticatedPayoutsIndexRoute: AuthenticatedPayoutsIndexRoute,
  AuthenticatedReferralsIndexRoute: AuthenticatedReferralsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AiWebsiteBootcampRoute: AiWebsiteBootcampRoute,
  CheckoutRoute: CheckoutRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authSignInRoute: authSignInRoute,
  authUpdatePasswordRoute: authUpdatePasswordRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  RefRefCodeRoute: RefRefCodeRoute,
  RefCallbackRoute: RefCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
